var feature = require('protractor-jasmine-cucumber').feature;

feature('Login/Registration')
    .scenario('Admin')
        .given('I go to "#/login"')
        .when('I enter "username" = "admin"')
        .and('I enter "password" = "admin"')
        .and('I click the "login_submit_button" button')
        .then('I should be on "#/index"')
        .then('I should be logged in as "Admin"')
    .scenario('User')
        .given('I go to "#/login"')
        .when('I enter "username" = "user"')
        .and('I enter "password" = "user"')
        .and('I click the "login_submit_button" button')
        .then('I should be on "#/index"')
        .then('I should be logged in as "User"')
    .scenario('User - wrong password')
        .given('I go to "#/login"')
        .when('I enter "username" = "user"')
        .and('I enter "password" = "qwe"')
        .and('I click the "login_submit_button" button')
        .then('I should be on "#/login"')
        .then('I should get an error "Wrong username and/or password!"')
    .scenario('Failed')
        .given('I go to "#/login"')
        .when('I enter "username" = "qwe"')
        .and('I enter "password" = "qwe"')
        .and('I click the "login_submit_button" button')
        .then('I should be on "#/login"')
        .then('I should get an error "Wrong username and/or password!"')
    .scenario('Registration')
        .given('I go to "#/register"')
        .when('I fill in new test user')
        .and('I click the "registration_submit_button" button')
        .then('I should be on "#/index"')
        .then('I should be logged in as new test user')
    .scenario('Registration - user already exists')
        .given('I go to "#/register"')
        .when('I fill in new test user')
        .and('I click the "registration_submit_button" button')
        .then('I should be on "#/register"')
        .then('I should get an error "User already exist"')
    .scenario('Registration - password check do not match')
        .given('I go to "#/register"')
        .when('I fill in new test user with wrong password check')
        .and('I click the "registration_submit_button" button')
        .then('I should be on "#/register"')
        .then('I should get an error "Password must be the same in both fields!"');