var feature = require('protractor-jasmine-cucumber').feature;

feature('Login')
    .scenario('Admin')
        .given('I go to "#/login"')
        .when('I enter "username" = "admin"')
        .and('I enter "password" = "admin"')
        .and('I click the button "Login"')
        .then('I should be on "#/index"')
        .then('I should be logged in as "Admin"')
    .scenario('User')
        .given('I go to "#/login"')
        .when('I enter "username" = "user"')
        .and('I enter "password" = "user"')
        .and('I click the button "Login"')
        .then('I should be on "#/index"')
        .then('I should be logged in as "User"')
    .scenario('User - wrong password')
        .given('I go to "#/login"')
        .when('I enter "username" = "user"')
        .and('I enter "password" = "qwe"')
        .and('I click the button "Login"')
        .then('I should be on "#/login"')
        .then('I should get an error "Wrong username and/or password!"')
    .scenario('User - wrong username')
        .given('I go to "#/login"')
        .when('I enter "username" = "qwe"')
        .and('I enter "password" = "qwe"')
        .and('I click the button "Login"')
        .then('I should be on "#/login"')
        .then('I should get an error "Wrong username and/or password!"')
    .scenario('User - logout')
        .given('I logged in as "user"/"user"')
        .when('I log out')
        .then('I am not logged in');