var feature = require('protractor-jasmine-cucumber').feature;

feature('Registration')
    .scenario('New Test User')
        .given('I go to "#!/register"')
        .when('I fill in new test user')
        .and('I click the button "Sign Up"')
        .then('I should be on "#!/index"')
        .and('I should get a message "User successfully registered!"')
        .and('I should be logged in as new test user')
    .scenario('User already exists')
        .given('I go to "#!/register"')
        .when('I fill in new test user')
        .and('I click the button "Sign Up"')
        .then('I should be on "#!/register"')
        .and('I should get an error "User already exist"')
    .scenario('Password check do not match')
        .given('I go to "#!/register"')
        .when('I fill in new test user with wrong password check')
        .and('I click the button "Sign Up"')
        .then('I should be on "#!/register"')
        .and('I should get an error "Password must be the same in both fields!"')
    .scenario('Email is not valid')
        .given('I go to "#!/register"')
        .when('I fill in new test user with wrong email')
        .and('I click the button "Sign Up"')
        .then('I should be on "#!/register"')
        .and('I should see email validator error');