var feature = require('protractor-jasmine-cucumber').feature;

feature('Users: Admin')
    .scenario('List')
        .given('I logged in as "admin"/"admin"')
        .and('I go to "#!/users"')
        .then('I should see a user list')
    .scenario('Create')
        .given('I logged in as "admin"/"admin"')
        .when('I create test user')
        .then('I should be on "#!/users"')
        .and('I should get a message "User successfully created!"')
        .and('I should see the new test user')
        .and('I should be able to login with test user v1')
    .scenario('Create with the same username')
        .given('I logged in as "admin"/"admin"')
        .when('I create test user')
        .then('I should be on "#!/user"')
        .and('I should get an error "User already exist"')
    .scenario('Update from list screen')
        .given('I logged in as "admin"/"admin"')
        .when('I update test user from list screen')
        .then('I should get a message "User successfully updated!"')
        .and('I should see updated test user v2')
    .scenario('Update from user screen')
        .given('I logged in as "admin"/"admin"')
        .when('I update test user from user screen')
        .then('I should get a message "User successfully updated!"')
        .and('I should see updated test user v3')
        .and('I should be able to login with test user v3')
    .scenario('Update from user screen - excluding password')
        .given('I logged in as "admin"/"admin"')
        .when('I update test user from user screen excluding password')
        .then('I should get a message "User successfully updated!"')
        .and('I should see updated test user v4')
        .and('I should be able to login with test user v4')
    .scenario('Delete test user')
        .given('I logged in as "admin"/"admin"')
        .and('I go to "#!/users"')
        .when('I delete test user')
        .then('I should get a message "User successfully deleted!"')
        .and('I should not see test user')
        .and('I should not be able to login with test user');